---
title: "Aggregation of cTWAS results"
author: "Lifan Liang"
date: "2024-07-24"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

Aggregate cTWAS results from NPD traits and investigate sharing

```{r,echo=F}
fs <- c("SCZ","Bipolar","Depression","Neuroticism","ADHD")
ress <- list()
for(f in fs) {
  temp <- readRDS(paste0("data/processed_",f,"_res4.rds"))
  rownames(temp) <- temp$genename
  ress[[f]] <- temp#[temp$PIP_sum>0.8,]
}
```




## Cell type distribution of significant genes

```{r, echo=F}
library(ggplot2)
count1 <- list()
for(n in names(ress)) {
  count1[[n]] <- data.frame(table(ress[[n]]$celltype))
  colnames(count1[[n]]) <- c("cell_type","gene_count")
  count1[[n]]$disease <- n
}
count1 <- do.call(rbind,count1)

ggplot(count1,aes(x=disease, y=gene_count, fill=cell_type)) + 
  geom_bar(position="stack", stat="identity") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

## Dynamic gene counts across cell types

```{r, echo=F}
ress[[3]]$PIP_diff <- rowSums(ress[[3]][,6:11]) - rowSums(ress[[3]][,3:5])
ress[[4]]$PIP_diff <- rowSums(ress[[4]][,6:10]) - rowSums(ress[[4]][,3:5])
ress[[5]]$PIP_diff <- rowSums(ress[[5]][,3:7])

dymcount = sapply(ress, function(x){sum(x$PIP_diff>0.5)})
statcount = sapply(ress, function(x){sum(x$PIP_diff<0.5)})
count2 <- data.frame(gene_count=c(dymcount,statcount), 
           disease=c(names(dymcount),names(statcount)),
           type=c(rep("dynamic",length(dymcount)), rep("static",length(statcount))))

ggplot(count2,aes(x=disease, y=gene_count, fill=type)) + 
  geom_bar(position="stack", stat="identity") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1))
```

```{r, echo=F}
ress1 <- lapply(ress, function(x) {
  c(rowSums(x[,grepl("0hr",colnames(x))]),
  rowSums(x[,grepl("1hr",colnames(x))]),
  rowSums(x[,grepl("6hr",colnames(x))]))
})

dymcount = sapply(ress, function(x){sum(x$PIP_diff>0.5)})
statcount = sapply(ress, function(x){sum(x$PIP_diff<0.5)})
count2 <- data.frame(gene_count=c(dymcount,statcount), 
           disease=c(names(dymcount),names(statcount)),
           type=c(rep("dynamic",length(dymcount)), rep("static",length(statcount))))

ggplot(count2,aes(x=disease, y=gene_count, fill=type)) + 
  geom_bar(position="stack", stat="identity") + 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  theme_classic()
```

## Significant gene distribution across the five traits

Not much sharing among traits.

```{r, echo=F}
library(pheatmap)

gene.univ <- unique(do.call(c, lapply(ress, function(x){x$genename})))
dat1 <- matrix(0,nrow=length(gene.univ),ncol=length(ress))
rownames(dat1)=gene.univ
colnames(dat1)=names(ress)
for(n in names(ress)) {
  dat1[rownames(ress[[n]]),n] <- ress[[n]]$PIP_sum
}
pheatmap(dat1, cluster_rows = F, cluster_cols = F)
```

## Enrichment analysis

### Three traits with PIP>0.8
```{r, echo=F}
library(enrichR)
library(dplyr)
gene.univ <- unique(do.call(c, lapply(ress[1:3], function(x){x$genename[x$PIP_sum>0.8]})))
enrich.res <- enrichr(gene.univ, "GO_Biological_Process_2023")
head(enrich.res$GO_Biological_Process_2023[-(5:8)],10) %>%
  DT::datatable() %>%
  DT::formatRound(columns=c('P.value', 'Adjusted.P.value'), digits=3)
```

### Three traits with PIP>0.5
```{r, echo=F}
library(enrichR)
library(dplyr)
gene.univ <- unique(do.call(c, lapply(ress[1:3], function(x){x$genename[x$PIP_sum>0.5]})))
enrich.res <- enrichr(gene.univ, "GO_Biological_Process_2023")
head(enrich.res$GO_Biological_Process_2023[-(5:8)],10) %>%
  DT::datatable() %>%
  DT::formatRound(columns=c('P.value', 'Adjusted.P.value'), digits=3)
```

### Five traits with PIP>0.8
```{r, echo=F}
library(enrichR)
library(dplyr)
gene.univ <- unique(do.call(c, lapply(ress, function(x){x$genename[x$PIP_sum>0.8]})))
enrich.res <- enrichr(gene.univ, "GO_Biological_Process_2023")
head(enrich.res$GO_Biological_Process_2023[-(5:8)],10) %>%
  DT::datatable() %>%
  DT::formatRound(columns=c('P.value', 'Adjusted.P.value'), digits=3)
```

### Five traits with PIP>0.5
```{r, echo=F}
library(enrichR)
library(dplyr)
gene.univ <- unique(do.call(c, lapply(ress, function(x){x$genename[x$PIP_sum>0.5]})))
enrich.res <- enrichr(gene.univ, "GO_Biological_Process_2023")
head(enrich.res$GO_Biological_Process_2023[-(5:8)],10) %>%
  DT::datatable() %>%
  DT::formatRound(columns=c('P.value', 'Adjusted.P.value'), digits=3)
```
